# Generated by Django 5.2.4 on 2025-08-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_edit', 'Can edit content'), ('can_create', 'Can create content')]},
        ),
    ]
